imports:
    - { resource: config_test.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true

web_profiler:
    toolbar: true

csa_guzzle:
    logger: true
    clients:
        local_test_api:
            config:
#                base_uri: "http://127.0.0.1:8000/app_acceptance.php/"
                # base_uri: "http://127.0.0.1:8000/"
                base_uri: "https://backend-symfony.herokuapp.com/"




parameters:
#    database_name: "db_acceptance"
    database_name: "symfonyreact"