security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory: #new line
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api_password_reset:
            pattern: ^/password/reset
            anonymous: true

        api_register:
            pattern: ^/register
            anonymous: true

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
            anonymous: true #add by me

        api_docs: #new lines
            pattern: ^/doc
            anonymous: true

    access_control:

        - { path: ^/register$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/reset,   role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/,                 role: IS_AUTHENTICATED_FULLY }
        - { path: ^/,                 roles: IS_AUTHENTICATED_ANONYMOUSLY} #new line
        - { path: ^/doc,              roles: IS_AUTHENTICATED_ANONYMOUSLY} #new line


